apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jenkins-infr-cls
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "895386959211"
    provider: eks
    region: us-east-1
    registry: 895386959211.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - key: dev
    owner: docttus
    repository: jenkins-cluster
  - key: staging
  - key: production
  ingress:
    domain: 52.73.99.16.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: docttus-bot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-jenkins-infr-cls-2022112222061436650000000b
  - name: reports
    url: s3://reports-jenkins-infr-cls-20221122220612973600000007
  - name: repository
    url: s3://repository-jenkins-infr-cls-20221122220612974000000008
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-east-1
      dynamoDBTable: vault-unseal-jenkins-infr-cls-PQSTDyjP
      kmsKeyId: 3828c4fc-2bfa-4a6e-b0c1-f9c829519600
      kmsRegion: us-east-1
      s3Bucket: vault-unseal-jenkins-infr-cls-20221122220612974200000009
      s3Region: us-east-1
  webhook: lighthouse
